package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"testing"
	"time"
)

func TestUpdate(t *testing.T) {

	apiAddr := "https://www.bing.com/HPImageArchive.aspx?format=js&n=1&pid=hp&mkt=en-US&uhd=1&uhdwidth=384&uhdheight=216"

	resp, err := http.Get(apiAddr)
	if err != nil {
		t.Error(err)
	}

	jsonmsg := AutoGenerated{}
	data, _ := io.ReadAll(resp.Body)
	json.Unmarshal(data, &jsonmsg)

	// download image
	resp, err = http.Get(bingURL + jsonmsg.Images[0].Urlbase + "_UHD.jpg")
	if err != nil {
		t.Error(err)
		return
	}
	defer resp.Body.Close()

	if resp.StatusCode != 200 {
		t.Error("download failed")
		return
	}

	// open a file and store the image
	testFile, err := os.Create("test.jpg")
	if err != nil {
		t.Error(err)
		return
	}

	_, err = io.Copy(testFile, resp.Body)
	if err != nil {
		t.Error(err)
		return
	}

}

func TestGetWallpapers(t *testing.T) {
	var err error
	//d, err := time.Parse("2006-01", "2023-04")
	if err != nil {
		t.Error(err)
	}

	results := getWallpapers(time.Now())
	fmt.Println(len(results))
}
